system:
 vehicle_description:
  flags:
   running: true
   lidar_initialized: false
   obstacles_initialized: false
   postion_update_external: true
   obstacles_initialized: false
 nloptcontrol_planner:
  namespace: nloptcontrol
  flags:
   running: true
   initilized: false
   known_environment: false
   3DOF_plant: true
   goal_attained: false
 obstacle_detector:
  flags:
   running: true
   initialized: false

 initialized: false
 paused: true
